### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by iamdiwang** [KatyushaScarlet/RGSS-Extractor#1]
very simple but somehow works , thankss <3

**Comment by KatyushaScarlet** [comment]
> very simple but somehow works , thankss <3

You're welcome, I just did a little bit of work :)

**Comment by roriloty** [comment]
hello this there a ways to compile it back together? like if i want to edit the game that already exist like adding a new character or item.

**Comment by KatyushaScarlet** [comment]
> hello this there a ways to compile it back together? like if i want to edit the game that already exist like adding a new character or item.

Of course you can!
For example, if the game was made by RPG Maker VX, you can export the original file from the "rgss2a" file and put it into the game directory.
Then, put a "game.rxproj" file into the game directory, and open it with RPG Maker VX.
